In [7]:
#song lyrics included in the code cause why not, also this is the cell meant for the data inputs
#THIS IS ME
LAST_NAME = "Yao"
STUDENT_ID = "TUPM-26-1186"
SEED_NUM = int(STUDENT_ID[-1]) #this is gonna be 6 again idk why i keep doing the full thing when i can just do this but whatever
FAVORITE_ARTIST = "BEN AND BEN"
#LOOK OUT CAUSE HERE I COME
import random
import pandas as pd
random.seed(SEED_NUM + len(FAVORITE_ARTIST))
#AND THEYRE MARCHING ONTO THE BEAT I DRUMMM
print(f"Inputs Loaded Successfully for: {LAST_NAME}")
print(f"Seed: {SEED_NUM} | Artist: {FAVORITE_ARTIST}")

Inputs Loaded Successfully for: Yao
Seed: 6 | Artist: BEN AND BEN

In [ ]:
#helped with ai kasi we're all cramming studying for midterms habang ginagawa namin po ito sa library

sources = [f"{LAST_NAME}_T{i}" for i in range(1, 6)]
categories = ["TEMPERATURE", "VOLTAGE", "CURRENT", "PRESSURE", "SPEED"]

raw_records = []

for source in sources:
    for cat in categories:
        base_val = round(random.uniform(10.0, 500.0) + sum(ord(c) for c in FAVORITE_ARTIST) % 50, 2)
        raw_records.append({"Test_Source": source, "Category": cat, "Measured_Value": base_val})

raw_records.append(raw_records[0].copy())
raw_records.append({"Test_Source": sources[0], "Category": "TEMPERATURE", "Measured_Value": 99.99})
raw_records.append({"Test_Source": sources[1], "Category": "VOLTAGE", "Measured_Value": 220.50})
df_raw = pd.DataFrame(raw_records)
print(f"Total Raw Records Generated: {len(df_raw)}")
display(df_raw.head(10))

print (display) #putitng this here for me to see it, also posterity

Total Raw Records Generated: 28

  Test_Source     Category  Measured_Value
0      Yao_T1  TEMPERATURE          266.77
1      Yao_T1      VOLTAGE          406.28
2      Yao_T1      CURRENT          481.64
3      Yao_T1     PRESSURE          152.92
4      Yao_T1        SPEED          386.39
5      Yao_T2  TEMPERATURE          356.07
6      Yao_T2      VOLTAGE          335.08
7      Yao_T2      CURRENT           64.98
8      Yao_T2     PRESSURE           24.20
9      Yao_T2        SPEED          199.24

<function display at 0x0000028B0ED5A610>

In [10]:
#Organizing cell, thanks Gemini!!


organized_df = df_raw.groupby(["Test_Source", "Category"])["Measured_Value"].agg(['count', 'mean', 'min', 'max']).reset_index()
organized_df.rename(columns={'count': 'Record_Count', 'mean': 'Average_Value', 'min': 'Min_Value', 'max': 'Max_Value'}, inplace=True)

display(organized_df)

   Test_Source     Category  Record_Count  Average_Value  Min_Value  Max_Value
0       Yao_T1      CURRENT             1     481.640000     481.64     481.64
1       Yao_T1     PRESSURE             1     152.920000     152.92     152.92
2       Yao_T1        SPEED             1     386.390000     386.39     386.39
3       Yao_T1  TEMPERATURE             3     211.176667      99.99     266.77
4       Yao_T1      VOLTAGE             1     406.280000     406.28     406.28
5       Yao_T2      CURRENT             1      64.980000      64.98      64.98
6       Yao_T2     PRESSURE             1      24.200000      24.20      24.20
7       Yao_T2        SPEED             1     199.240000     199.24     199.24
8       Yao_T2  TEMPERATURE             1     356.070000     356.07     356.07
9       Yao_T2      VOLTAGE             2     277.790000     220.50     335.08
10      Yao_T3      CURRENT             1     256.790000     256.79     256.79
11      Yao_T3     PRESSURE             1     166.540000     166.54     166.54
12      Yao_T3        SPEED             1     425.700000     425.70     425.70
13      Yao_T3  TEMPERATURE             1     376.730000     376.73     376.73
14      Yao_T3      VOLTAGE             1     134.670000     134.67     134.67
15      Yao_T4      CURRENT             1     500.240000     500.24     500.24
16      Yao_T4     PRESSURE             1      41.470000      41.47      41.47
17      Yao_T4        SPEED             1     409.180000     409.18     409.18
18      Yao_T4  TEMPERATURE             1     474.150000     474.15     474.15
19      Yao_T4      VOLTAGE             1     207.780000     207.78     207.78
20      Yao_T5      CURRENT             1     356.730000     356.73     356.73
21      Yao_T5     PRESSURE             1     284.860000     284.86     284.86
22      Yao_T5        SPEED             1     479.040000     479.04     479.04
23      Yao_T5  TEMPERATURE             1     439.910000     439.91     439.91
24      Yao_T5      VOLTAGE             1      84.950000      84.95      84.95

In [11]:
duplicates = df_raw[df_raw.duplicated(keep=False)]
print("--- Repeated Records Found ---")
display(duplicates)

distinct_sources = df_raw["Test_Source"].unique()
distinct_categories = df_raw["Category"].unique()
print(f"\nDistinct Test Sources ({len(distinct_sources)}): {list(distinct_sources)}")
print(f"Distinct Categories ({len(distinct_categories)}): {list(distinct_categories)}")

--- Repeated Records Found ---

   Test_Source     Category  Measured_Value
0       Yao_T1  TEMPERATURE          266.77
25      Yao_T1  TEMPERATURE          266.77

Distinct Test Sources (5): ['Yao_T1', 'Yao_T2', 'Yao_T3', 'Yao_T4', 'Yao_T5']
Distinct Categories (5): ['TEMPERATURE', 'VOLTAGE', 'CURRENT', 'PRESSURE', 'SPEED']

In [12]:
categorical_summary = df_raw.groupby("Category")["Measured_Value"].agg(
    Total_Entries="count",
    Mean_Value="mean",
    Median_Value="median",
    Std_Dev="std",
    Max_Value="max",
    Min_Value="min"
).reset_index()

display(categorical_summary)

,Category,Total_Entries,Mean_Value,Median_Value,Std_Dev,Max_Value,Min_Value
0,CURRENT,5,332.076000,356.73,179.070235,500.24,64.98
1,PRESSURE,5,133.998000,152.92,105.822255,284.86,24.20
2,SPEED,5,379.910000,409.18,106.611272,479.04,199.24
3,TEMPERATURE,7,325.770000,356.07,126.818889,474.15,99.99
4,VOLTAGE,6,231.543333,214.14,120.675966,406.28,84.95

In [13]:
ordered_results = df_raw.sort_values(by=["Category", "Measured_Value"], ascending=[True, False]).reset_index(drop=True)

display(ordered_results.head(15))

   Test_Source  Category  Measured_Value
0       Yao_T4   CURRENT          500.24
1       Yao_T1   CURRENT          481.64
2       Yao_T5   CURRENT          356.73
3       Yao_T3   CURRENT          256.79
4       Yao_T2   CURRENT           64.98
5       Yao_T5  PRESSURE          284.86
6       Yao_T3  PRESSURE          166.54
7       Yao_T1  PRESSURE          152.92
8       Yao_T4  PRESSURE           41.47
9       Yao_T2  PRESSURE           24.20
10      Yao_T5     SPEED          479.04
11      Yao_T3     SPEED          425.70
12      Yao_T4     SPEED          409.18
13      Yao_T1     SPEED          386.39
14      Yao_T2     SPEED          199.24

In [14]:
final_dataset = df_raw.drop_duplicates().reset_index(drop=True)

print("==========================================")
print(" FINAL ORGANIZED & SUMMARIZED TEST DATASET")
print("==========================================")
print(f"Total Clean Records: {len(final_dataset)}")
display(final_dataset)

==========================================
 FINAL ORGANIZED & SUMMARIZED TEST DATASET
==========================================
Total Clean Records: 27

   Test_Source     Category  Measured_Value
0       Yao_T1  TEMPERATURE          266.77
1       Yao_T1      VOLTAGE          406.28
2       Yao_T1      CURRENT          481.64
3       Yao_T1     PRESSURE          152.92
4       Yao_T1        SPEED          386.39
5       Yao_T2  TEMPERATURE          356.07
6       Yao_T2      VOLTAGE          335.08
7       Yao_T2      CURRENT           64.98
8       Yao_T2     PRESSURE           24.20
9       Yao_T2        SPEED          199.24
10      Yao_T3  TEMPERATURE          376.73
11      Yao_T3      VOLTAGE          134.67
12      Yao_T3      CURRENT          256.79
13      Yao_T3     PRESSURE          166.54
14      Yao_T3        SPEED          425.70
15      Yao_T4  TEMPERATURE          474.15
16      Yao_T4      VOLTAGE          207.78
17      Yao_T4      CURRENT          500.24
18      Yao_T4     PRESSURE           41.47
19      Yao_T4        SPEED          409.18
20      Yao_T5  TEMPERATURE          439.91
21      Yao_T5      VOLTAGE           84.95
22      Yao_T5      CURRENT          356.73
23      Yao_T5     PRESSURE          284.86
24      Yao_T5        SPEED          479.04
25      Yao_T1  TEMPERATURE           99.99
26      Yao_T2      VOLTAGE          220.50

In [15]:
#just wanted to add that most of these appendixes are crammed and powered with AI but theyre still really fun to learn from.
#Thank you po sir and I appreciate all of these lab works even if I find myself rellying on AI and Geeks4Geeks for them.