In [1]:
import random
import pandas as pd
import numpy as np

LAST_NAME = "Yao"
STUDENT_ID = "TUPM-26-1186"
SEED_NUM = int(STUDENT_ID[-1]) #this is gonna be 6 again idk why i keep doing the full thing when i can just do this but whatever
FAVORITE_ARTIST = "BEN AND BEN"#I just imported these from first appendix cause they all use the same inputs nmn

random.seed(SEED_NUM + len(FAVORITE_ARTIST))

print(f"Inputs Loaded Successfully for: {LAST_NAME}")
print(f"Seed: {SEED_NUM} | Artist: {FAVORITE_ARTIST}")

Inputs Loaded Successfully for: Yao
Seed: 6 | Artist: BEN AND BEN

In [2]:
student_names = [f"{LAST_NAME}_Student_{chr(65+i)}" for i in range(5)]
subjects = ["PROGRAMMING", "MATHEMATICS", "ELECTRONICS", "PHYSICS", "ENGLISH"]
raw_records = []
for student in student_names:
    for subject in subjects:
        base_score = int((SEED_NUM + sum(ord(c) for c in FAVORITE_ARTIST) * random.randint(1, 3)) % 51) + 50
        score = min(max(base_score, 50), 100)
        raw_records.append({
            "Student_Name": student,
            "Subject": subject,
            "Score": score
            })


raw_records.append(raw_records[0].copy())
raw_records.append({
    "Student_Name": student_names[0],
    "Subject": "PROGRAMMING",
    "Score": np.nan
})

df_perf_raw = pd.DataFrame(raw_records)
print(f"Total Raw Records Generated: {len(df_perf_raw)}")
display(df_perf_raw.head(10))

Total Raw Records Generated: 27

    Student_Name      Subject  Score
0  Yao_Student_A  PROGRAMMING   68.0
1  Yao_Student_A  MATHEMATICS   81.0
2  Yao_Student_A  ELECTRONICS   81.0
3  Yao_Student_A      PHYSICS   81.0
4  Yao_Student_A      ENGLISH   81.0
5  Yao_Student_B  PROGRAMMING   94.0
6  Yao_Student_B  MATHEMATICS   68.0
7  Yao_Student_B  ELECTRONICS   68.0
8  Yao_Student_B      PHYSICS   68.0
9  Yao_Student_B      ENGLISH   68.0

In [3]:
df_clean_org = df_perf_raw.drop_duplicates().copy()

student_pivot = df_clean_org.pivot_table(index="Student_Name", columns="Subject", values="Score")
display(student_pivot)

#I like how Gemini handles the usage of cells, they have a raw data cell and then a clean up cell its really cool

Subject        ELECTRONICS  ENGLISH  MATHEMATICS  PHYSICS  PROGRAMMING
Student_Name
Yao_Student_A         81.0     81.0         81.0     81.0         68.0
Yao_Student_B         68.0     68.0         68.0     68.0         94.0
Yao_Student_C         94.0     81.0         94.0     94.0         81.0
Yao_Student_D         81.0     81.0         81.0     68.0         68.0
Yao_Student_E         68.0     94.0         68.0     81.0         68.0

In [4]:
def get_performance_category(score):
    if pd.isna(score):
        return "Incomplete"
    elif score >= 90:
        return "Excellent"
    elif score >= 80:
        return "Above Average"
    elif score >= 75:
        return "Average"
    else:
        return "Passing"

df_perf_raw["Performance_Category"] = df_perf_raw["Score"].apply(get_performance_category)
repeated_records = df_perf_raw[df_perf_raw.duplicated(keep=False)]
print("--- Repeated Records Found ---")
display(repeated_records)
incomplete_records = df_perf_raw[df_perf_raw["Score"].isna()]
print("\n--- Incomplete Records Found ---")
display(incomplete_records)

--- Repeated Records Found ---

     Student_Name      Subject  Score Performance_Category
0   Yao_Student_A  PROGRAMMING   68.0              Passing
25  Yao_Student_A  PROGRAMMING   68.0              Passing

--- Incomplete Records Found ---

     Student_Name      Subject  Score Performance_Category
26  Yao_Student_A  PROGRAMMING    NaN           Incomplete

In [5]:
print("--- Summary by Student ---")
student_summary = df_perf_raw.groupby("Student_Name")["Score"].agg(
    Total_Subjects_Taken="count",
    Average_Score="mean",
    Highest_Score="max",
    Lowest_Score="min"
).reset_index()
display(student_summary)

print("\n--- Summary by Subject ---")
subject_summary = df_perf_raw.groupby("Subject")["Score"].agg(
    Total_Students="count",
    Average_Score="mean",
    Highest_Score="max",
    Lowest_Score="min"
).reset_index()
display(subject_summary)

--- Summary by Student ---

,Student_Name,Total_Subjects_Taken,Average_Score,Highest_Score,Lowest_Score
0,Yao_Student_A,6,76.666667,81.0,68.0
1,Yao_Student_B,5,73.200000,94.0,68.0
2,Yao_Student_C,5,88.800000,94.0,81.0
3,Yao_Student_D,5,75.800000,81.0,68.0
4,Yao_Student_E,5,75.800000,94.0,68.0

--- Summary by Subject ---

       Subject  Total_Students  Average_Score  Highest_Score  Lowest_Score
0  ELECTRONICS               5           78.4           94.0          68.0
1      ENGLISH               5           81.0           94.0          68.0
2  MATHEMATICS               5           78.4           94.0          68.0
3      PHYSICS               5           78.4           94.0          68.0
4  PROGRAMMING               6           74.5           94.0          68.0

In [6]:
ordered_performance = df_perf_raw.sort_values(by=["Student_Name", "Score"], ascending=[True, False]).reset_index(drop=True)

print("==================================================")
print(" FINAL CONSOLIDATED STUDENT PERFORMANCE REPORT")
print("==================================================")
display(ordered_performance)

==================================================
 FINAL CONSOLIDATED STUDENT PERFORMANCE REPORT
==================================================

     Student_Name      Subject  Score Performance_Category
0   Yao_Student_A  MATHEMATICS   81.0        Above Average
1   Yao_Student_A  ELECTRONICS   81.0        Above Average
2   Yao_Student_A      PHYSICS   81.0        Above Average
3   Yao_Student_A      ENGLISH   81.0        Above Average
4   Yao_Student_A  PROGRAMMING   68.0              Passing
5   Yao_Student_A  PROGRAMMING   68.0              Passing
6   Yao_Student_A  PROGRAMMING    NaN           Incomplete
7   Yao_Student_B  PROGRAMMING   94.0            Excellent
8   Yao_Student_B  MATHEMATICS   68.0              Passing
9   Yao_Student_B  ELECTRONICS   68.0              Passing
10  Yao_Student_B      PHYSICS   68.0              Passing
11  Yao_Student_B      ENGLISH   68.0              Passing
12  Yao_Student_C  MATHEMATICS   94.0            Excellent
13  Yao_Student_C  ELECTRONICS   94.0            Excellent
14  Yao_Student_C      PHYSICS   94.0            Excellent
15  Yao_Student_C  PROGRAMMING   81.0        Above Average
16  Yao_Student_C      ENGLISH   81.0        Above Average
17  Yao_Student_D  MATHEMATICS   81.0        Above Average
18  Yao_Student_D  ELECTRONICS   81.0        Above Average
19  Yao_Student_D      ENGLISH   81.0        Above Average
20  Yao_Student_D  PROGRAMMING   68.0              Passing
21  Yao_Student_D      PHYSICS   68.0              Passing
22  Yao_Student_E      ENGLISH   94.0            Excellent
23  Yao_Student_E      PHYSICS   81.0        Above Average
24  Yao_Student_E  PROGRAMMING   68.0              Passing
25  Yao_Student_E  MATHEMATICS   68.0              Passing
26  Yao_Student_E  ELECTRONICS   68.0              Passing