In [1]:
import random
import pandas as pd

LAST_NAME = "Yao"
STUDENT_ID = "TUPM-26-1186"
SEED_NUM = int(STUDENT_ID[-1]) #this is gonna be 6 again idk why i keep doing the full thing when i can just do this but whatever
FAVORITE_ARTIST = "BEN AND BEN"#I just imported these from first appendix cause they all use the same inputs nmn

random.seed(SEED_NUM + len(FAVORITE_ARTIST))

print(f"Inputs Loaded Successfully for: {LAST_NAME}")
print(f"Seed: {SEED_NUM} | Artist: {FAVORITE_ARTIST}")

Inputs Loaded Successfully for: Yao
Seed: 6 | Artist: BEN AND BEN

In [2]:
customers = [f"{LAST_NAME}_C{i}" for i in range(1, 6)]
products_prices = {
    "NOTEBOOK": 50.00,
    "PEN": 15.50,
    "USB": 250.00,
    "HEADPHONES": 750.00,
    "CALCULATOR": 1200.00
}

raw_transactions = []

for customer in customers:
    for product in products_prices.keys():
        qty = int((SEED_NUM + sum(ord(c) for c in FAVORITE_ARTIST)) % 5) + 1
        raw_transactions.append({
            "Customer": customer,
            "Product": product,
            "Quantity": qty,
            "Unit_Price": products_prices[product]
        })
raw_transactions.append(raw_transactions[0].copy())

df_trans_raw = pd.DataFrame(raw_transactions)
print(f"Total Raw Transactions Generated: {len(df_trans_raw)}")
display(df_trans_raw.head(10))

Total Raw Transactions Generated: 26

  Customer     Product  Quantity  Unit_Price
0   Yao_C1    NOTEBOOK         3        50.0
1   Yao_C1         PEN         3        15.5
2   Yao_C1         USB         3       250.0
3   Yao_C1  HEADPHONES         3       750.0
4   Yao_C1  CALCULATOR         3      1200.0
5   Yao_C2    NOTEBOOK         3        50.0
6   Yao_C2         PEN         3        15.5
7   Yao_C2         USB         3       250.0
8   Yao_C2  HEADPHONES         3       750.0
9   Yao_C2  CALCULATOR         3      1200.0

In [3]:
df_trans_raw["Total_Value"] = df_trans_raw["Quantity"] * df_trans_raw["Unit_Price"]

df_organized = df_trans_raw[["Customer", "Product", "Quantity", "Unit_Price", "Total_Value"]].copy()

total_dataset_value = df_organized["Total_Value"].sum()
print(f"Overall Dataset Transaction Value: ${total_dataset_value:,.2f}\n")
display(df_organized.head(10))

Overall Dataset Transaction Value: $34,132.50

  Customer     Product  Quantity  Unit_Price  Total_Value
0   Yao_C1    NOTEBOOK         3        50.0        150.0
1   Yao_C1         PEN         3        15.5         46.5
2   Yao_C1         USB         3       250.0        750.0
3   Yao_C1  HEADPHONES         3       750.0       2250.0
4   Yao_C1  CALCULATOR         3      1200.0       3600.0
5   Yao_C2    NOTEBOOK         3        50.0        150.0
6   Yao_C2         PEN         3        15.5         46.5
7   Yao_C2         USB         3       250.0        750.0
8   Yao_C2  HEADPHONES         3       750.0       2250.0
9   Yao_C2  CALCULATOR         3      1200.0       3600.0

In [4]:
repeated_purchases = df_organized[df_organized.duplicated(keep=False)]
print("--- Repeated Purchases Found ---")
display(repeated_purchases)

distinct_customers = df_organized["Customer"].unique()
distinct_products = df_organized["Product"].unique()

print(f"\nDistinct Customers ({len(distinct_customers)}): {list(distinct_customers)}")
print(f"Distinct Products ({len(distinct_products)}): {list(distinct_products)}")

--- Repeated Purchases Found ---

   Customer   Product  Quantity  Unit_Price  Total_Value
0    Yao_C1  NOTEBOOK         3        50.0        150.0
25   Yao_C1  NOTEBOOK         3        50.0        150.0

Distinct Customers (5): ['Yao_C1', 'Yao_C2', 'Yao_C3', 'Yao_C4', 'Yao_C5']
Distinct Products (5): ['NOTEBOOK', 'PEN', 'USB', 'HEADPHONES', 'CALCULATOR']

In [5]:
print("--- Customer Summaries ---")
customer_summary = df_organized.groupby("Customer").agg(
    Total_Transactions=("Product", "count"),
    Total_Items_Bought=("Quantity", "sum"),
    Total_Spent=("Total_Value", "sum")
).reset_index()
display(customer_summary)

print("\n--- Product Summaries ---")
product_summary = df_organized.groupby("Product").agg(
    Total_Units_Sold=("Quantity", "sum"),
    Times_Purchased=("Customer", "count"),
    Total_Revenue=("Total_Value", "sum")
).reset_index()
display(product_summary)

--- Customer Summaries ---

  Customer  Total_Transactions  Total_Items_Bought  Total_Spent
0   Yao_C1                   6                  18       6946.5
1   Yao_C2                   5                  15       6796.5
2   Yao_C3                   5                  15       6796.5
3   Yao_C4                   5                  15       6796.5
4   Yao_C5                   5                  15       6796.5

--- Product Summaries ---

      Product  Total_Units_Sold  Times_Purchased  Total_Revenue
0  CALCULATOR                15                5        18000.0
1  HEADPHONES                15                5        11250.0
2    NOTEBOOK                18                6          900.0
3         PEN                15                5          232.5
4         USB                15                5         3750.0

In [6]:
ordered_transactions = df_organized.sort_values(by="Total_Value", ascending=False).reset_index(drop=True)

print("======================================================")
print(" FINAL CONSOLIDATED TRANSACTION REPORT")
print("======================================================")
display(ordered_transactions)

======================================================
 FINAL CONSOLIDATED TRANSACTION REPORT
======================================================

   Customer     Product  Quantity  Unit_Price  Total_Value
0    Yao_C2  CALCULATOR         3      1200.0       3600.0
1    Yao_C1  CALCULATOR         3      1200.0       3600.0
2    Yao_C4  CALCULATOR         3      1200.0       3600.0
3    Yao_C5  CALCULATOR         3      1200.0       3600.0
4    Yao_C3  CALCULATOR         3      1200.0       3600.0
5    Yao_C2  HEADPHONES         3       750.0       2250.0
6    Yao_C3  HEADPHONES         3       750.0       2250.0
7    Yao_C1  HEADPHONES         3       750.0       2250.0
8    Yao_C5  HEADPHONES         3       750.0       2250.0
9    Yao_C4  HEADPHONES         3       750.0       2250.0
10   Yao_C5         USB         3       250.0        750.0
11   Yao_C2         USB         3       250.0        750.0
12   Yao_C4         USB         3       250.0        750.0
13   Yao_C3         USB         3       250.0        750.0
14   Yao_C1         USB         3       250.0        750.0
15   Yao_C5    NOTEBOOK         3        50.0        150.0
16   Yao_C1    NOTEBOOK         3        50.0        150.0
17   Yao_C2    NOTEBOOK         3        50.0        150.0
18   Yao_C1    NOTEBOOK         3        50.0        150.0
19   Yao_C4    NOTEBOOK         3        50.0        150.0
20   Yao_C3    NOTEBOOK         3        50.0        150.0
21   Yao_C1         PEN         3        15.5         46.5
22   Yao_C2         PEN         3        15.5         46.5
23   Yao_C3         PEN         3        15.5         46.5
24   Yao_C4         PEN         3        15.5         46.5
25   Yao_C5         PEN         3        15.5         46.5